#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HackAtHomeClient.Resource", IsApplication=true)]

namespace HackAtHomeClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HackAtHome.CustomAdapters.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.CustomAdapters.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.Entities.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.Entities.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.SAL.Resource.Animation.slide_in_right = global::HackAtHomeClient.Resource.Animation.slide_in_right;
			global::HackAtHome.SAL.Resource.Animation.slide_out_left = global::HackAtHomeClient.Resource.Animation.slide_out_left;
			global::HackAtHome.SAL.Resource.Drawable.ic_arrow_back = global::HackAtHomeClient.Resource.Drawable.ic_arrow_back;
			global::HackAtHome.SAL.Resource.Id.webview = global::HackAtHomeClient.Resource.Id.webview;
			global::HackAtHome.SAL.Resource.Layout.activity_webview = global::HackAtHomeClient.Resource.Layout.activity_webview;
			global::HackAtHome.SAL.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.SAL.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.SAL.Resource.String.title_activity_webview = global::HackAtHomeClient.Resource.String.title_activity_webview;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Luisito = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060011
			public const int btnValidate = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int imageView1 = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout1 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout2 = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int linearLayout3 = 2131099666;
			
			// aapt resource value: 0x7f060009
			public const int listView1 = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int textView1 = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int textView2 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int tvAprobado = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int tvLab = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int tvUSER = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int txtDescripcion = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int txtEmail = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int txtLabStatus = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int txtNomLab = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int txtPass = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int txtUserNomLab = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int webView1 = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int webview = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LabInfo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListaLabs = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItemLabs = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int Contra = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int Correo = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int Descripcion = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int Evidencia = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int Validar = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_webview = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
